### ISSUE TITLE
Strain Level Database

### ISSUE THREAD

**Issue by punnettsun** [muellan/metacache#13]
Hello,

I noticed that MetaCache can classify reads at the sequence level. If I had my own strain level database, would I be able to use MetaCache to classify reads at strain level?

Thank you.

**Comment by muellan** [comment]
Hi,

yes, it's possible to classify at any level, if the reference sequences/genomes are annotated accordingly. 

We didn't do many systematic tests below species level. So I can't point you to any publication regarding what levels of sensitivity or precision to expect with the default settings. That said, I would first try it using the default settings.
If too many reads are unmapped, you could increase the sketch size (command line parameter '-sketchlen') when building the database. This should increase sensitivity and precision at the expense of higher memory consumption.

**Comment by punnettsun** [comment]
Great, thank you for the clarification and for the quick response!
