### ISSUE TITLE
Allow for more threads?

### ISSUE THREAD

**Issue by punnettsun** [muellan/metacache#16]
Hi, 

I tried to run the database build, but it seems that my machine is only running MetaCache on a single thread. Is there a way to increase this? I do not see an argument for specifying threads in MetaCache.

Thanks.

**Comment by muellan** [comment]
I'm sorry, but only the query mode is multi-threaded, the database build is not multi-threaded in version 1.x.x

**Comment by punnettsun** [comment]
I see. Do you have an estimate for how long it might take to build the complete genomes in RefSeq by any chance?

**Comment by muellan** [comment]
On our machines it takes a bit more than an hour to build a database containing all complete bacterial, viral and archaea genomes from the latest RefSeq.

**Comment by punnettsun** [comment]
Thank you. Can I possibly get your email to email you about the specs I am using to build the database?

**Comment by muellan** [comment]
Sure, 4 hours sounds very odd indeed.

muellan@uni-mainz.de

**Comment by muellan** [comment]
I'll have a look at it tomorrow, it's already past 10 pm here :-)

**Comment by punnettsun** [comment]
Great thank you!

**Comment by ChillarAnand** [comment]
Did you find any bugs related to this?

I am trying to build a custom database and the build is taking ~50 hours. I am looking for ways to speed this upl

**Comment by punnettsun** [comment]
Sorry, but I unfortunately do not have access to the email domain I used at the time to look back at mine and Muellan’s conversation. I believe there was something on my end that was causing the issue with the database build.

I hope you will figure out the issue soon!
