### ISSUE TITLE
Database load times highly and unexpectedly non-linear

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [muellan/metacache#22]
Hi,

Thanks again for your work on MetaCache. I have noticed something a bit strange with the new version (MetaCache 2.0) where database loading takes much longer than I would expect (without any signs of I/O contention in iotop). The problem seems especially bad once the database loading % exceeds 90%. Loading from 0 to 90% seems to comprise ~20% of the load time, followed by the remaining 10% of the database. I am basing these percentages off of the stderr log, see attached for a representative log.

The actual analysis seems fast once it gets going. As it stands, I think I am spending about 75% of the time per sample just reading the database, but I am not sure why. Do you have any suggestions about how to improve sample throughput? I know completion percentages are usually off but I'm not sure how to debug further.

[metacache_stderr.log](https://github.com/muellan/metacache/files/6919136/metacache_stderr.log)

**Comment by jdwinkler-lanzatech** [comment]
In case it helps, I am using a database built in July 2021 from Refseq with archaeal/bacterial genomes.

**Comment by Funatiq** [comment]
Hi! I will investigate the issue tomorrow. Could you test if reducing the load factor (e.g. "-max-load-fac 0.7") does improve the loading time?

**Comment by jdwinkler-lanzatech** [comment]
Sure, I'll give that a shot.

**Comment by jdwinkler-lanzatech** [comment]
The speed appears to be about the same when using the -max-load-fac 0.7 flag versus default.

**Comment by Funatiq** [comment]
I found a bug in our code where the wrong load factor is set for the query mode. The fix will be pushed soon.

**Comment by jdwinkler-lanzatech** [comment]
Great, thanks.

**Comment by jdwinkler-lanzatech** [comment]
Just wanted to confirm that the fix works for me for posterity. Thanks again!
