### ISSUE TITLE
Enhancement: Provide NCBI taxids in output

### ISSUE THREAD

**Issue by sjaenick** [muellan/metacache#3]
The rank/tax. name combination is not necessarily unique; would it be possible to
include NCBI taxids as an additional output column?

**Comment by muellan** [comment]
You mean for the mapping result? With the command line argument "-taxids" the NCBI taxon id will be printed in parenthesis after the rang and name. With "-taxids-only" it will print "rank:taxid".

**Comment by sjaenick** [comment]
perfect, thanks
