### ISSUE TITLE
Database Build Files

### ISSUE THREAD

**Issue by punnettsun** [muellan/metacache#30]
Hi,

I had built a database for the GTDB, but when I check the database, all I see are the following files in my main non-database directory: `GTDB_DB.cache0` & `GTDB_DB.meta`
I am wondering if these are the files I will need to use to classify my fastq files?

This is the command I used: `./metacache build GTDB_DB /path/to/genomes/ -taxonomy /path/to/custom/taxonomy/`

Thank you.

**Comment by Funatiq** [comment]
Hi,

the name and path you choose for the database when building is the same you need to use for the query:
Build: `./metacache build GTDB_DB /path/to/genomes/ -taxonomy /path/to/custom/taxonomy/`
Query: `./metacache query GTDB_DB /path/to/reads/`

The `GTDB_DB.cache0` and `GTDB_DB.meta` files both belong to the database. You can move them to another directory if you want.

If you want to build or query the database in another directory:
Build: `./metacache build /database-directory/GTDB_DB /path/to/genomes/ -taxonomy /path/to/custom/taxonomy/`
Query: `./metacache query /database-directory/GTDB_DB /path/to/reads/`

For other options please see the README and documentation.

**Comment by punnettsun** [comment]
Thank you!
