### ISSUE TITLE
Make throws the Invalid Option error if multiple macros are passed

### ISSUE THREAD

**Issue by banderoz** [muellan/metacache#34]
Hi there!

When I try building the `metacache` package (v2.2.3) with multiple macros, `make` throws the `invalid option` error:
![image](https://user-images.githubusercontent.com/48513784/184165771-b28370dc-5103-40c3-9d31-fdc4298dcc73.png)

Seems like `$(MACROS)` should be quoted here: https://github.com/muellan/metacache/blob/532a737ffca173e264a28b8349a8da98cbf0aeb6/Makefile#L136

For now, I build `metacache` by running this command directly:
`make release_dummy DIR=build_release ARTIFACT=metacache MACROS="-DMC_TARGET_ID_TYPE=uint32_t -DMC_WINDOW_ID_TYPE=uint32_t"`

BR,
Zulfat

**Comment by Funatiq** [comment]
Thank you for your report. It will be fixed in the next version.
