### ISSUE TITLE
GPU version on bioconda

### ISSUE THREAD

**Issue by fgvieira** [muellan/metacache#38]
Dear all,

is there a GPU version of `metacache` on `bioconda`?

Can we also define `MC_KMER_TYPE` for GPU? Beacuse from the code it doesn't look like it:
https://github.com/muellan/metacache/blob/4c6db912f92b065ac36d1121a0d4849582896fa3/src/config.h#L44-L48

**Comment by muellan** [comment]
> is there a GPU version of `metacache` on `bioconda`?

Not that I'm aware of.

> Can we also define `MC_KMER_TYPE` for GPU?

No, the GPU version only supports kmers of length 16 (for various space and efficiency reasons).

**Comment by muellan** [comment]
Kraken and Kraken2 use mapping strategies that are different from MetaCache's. While Kraken counts Taxon hits based on single kmers, MetaCache uses multiple kmers within a small region ("window") and thus doesn't require long kmers.

If you want to increase precision you can use the `-hitmin <#kmers>` option (the default is 4 if I remember correctly) which controls how many kmers in a window are needed for a read to be classified.
