### ISSUE TITLE
separator not properly handled in the output

### ISSUE THREAD

**Issue by leoqiang** [muellan/metacache#7]
I tried to use tab as separator to set '-separator "\t"' parameter for query. However, the control sequence '\t' is literally printed in the output, instead of converted into tab.

e.g.,  ERR024951.132\tspecies\tKlebsiella pneumoniae\t573

**Comment by leoqiang** [comment]
I finally set the separator properly by using "$'\t'". However, it might be much easier if "\t" can be directly supported as in the other language.

**Comment by muellan** [comment]
Your shell (e.g., Bash) handles, how the command line argument characters are passed to an application. I as application developer don't have any influence on that. You have to use whatever convention your shell requires. In Bash that would be ´$'\t'´.

**Comment by muellan** [comment]
Well, maybe I could postprocess the command line args and replace ` \t` with a tab character. I guess that would be more comfortable for users.

**Comment by leoqiang** [comment]
Although I figure it out, the modification will surely benefit general users. Thanks.

**Comment by muellan** [comment]
Finally added code (see [this commit](https://github.com/muellan/metacache/commit/c47f6586843b0c524d5bcbe970e4c51b8c979c09)) that sanitizes the input of the `-separator <string>` option which resolves this issue.
