### ISSUE TITLE
target limit: number of genomes or sequences?

### ISSUE THREAD

**Issue by dparks1134** [muellan/metacache#9]
Hi. Is the target limit set by the `DMC_TARGET_ID_TYP` data type the maximum number of genome assemblies or the maximum number of contigs/scaffolds?

**Comment by Funatiq** [comment]
Hi! It's the maximum number of sequences (contigs, scaffolds, ...). Each sequence gets a separate target ID.

**Comment by dparks1134** [comment]
Great - thanks!
